(cl:in-package rtabmap_ros-msg)
(cl:export '(ID-VAL
          ID
          MAPID-VAL
          MAPID
          WEIGHT-VAL
          WEIGHT
          STAMP-VAL
          STAMP
          LABEL-VAL
          LABEL
          POSE-VAL
          POSE
          GROUNDTRUTHPOSE-VAL
          GROUNDTRUTHPOSE
          IMAGE-VAL
          IMAGE
          DEPTH-VAL
          DEPTH
          FX-VAL
          FX
          FY-VAL
          FY
          CX-VAL
          CX
          CY-VAL
          CY
          BASELINE-VAL
          BASELINE
          LOCALTRANSFORM-VAL
          LOCALTRANSFORM
          LASERSCAN-VAL
          LASERSCAN
          LASERSCANMAXPTS-VAL
          LASERSCANMAXPTS
          LASERSCANMAXRANGE-VAL
          LASERSCANMAXRANGE
          USERDATA-VAL
          USERDATA
          WORDIDS-VAL
          WORDIDS
          WORDKPTS-VAL
          WORDKPTS
          WORDPTS-VAL
          WORDPTS
))