(cl:in-package rtabmap_ros-msg)
(cl:export '(HEADER-VAL
          HEADER
          LOST-VAL
          LOST
          MATCHES-VAL
          MATCHES
          INLIERS-VAL
          INLIERS
          VARIANCE-VAL
          VARIANCE
          FEATURES-VAL
          FEATURES
          LOCALMAPSIZE-VAL
          LOCALMAPSIZE
          TIMEESTIMATION-VAL
          TIMEESTIMATION
          TIMEPARTICLEFILTERING-VAL
          TIMEPARTICLEFILTERING
          STAMP-VAL
          STAMP
          INTERVAL-VAL
          INTERVAL
          DISTANCETRAVELLED-VAL
          DISTANCETRAVELLED
          TYPE-VAL
          TYPE
          WORDSKEYS-VAL
          WORDSKEYS
          WORDSVALUES-VAL
          WORDSVALUES
          WORDMATCHES-VAL
          WORDMATCHES
          WORDINLIERS-VAL
          WORDINLIERS
          LOCALMAPKEYS-VAL
          LOCALMAPKEYS
          LOCALMAPVALUES-VAL
          LOCALMAPVALUES
          REFCORNERS-VAL
          REFCORNERS
          NEWCORNERS-VAL
          NEWCORNERS
          CORNERINLIERS-VAL
          CORNERINLIERS
          TRANSFORM-VAL
          TRANSFORM
          TRANSFORMFILTERED-VAL
          TRANSFORMFILTERED
))